server:
  port: 9090
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gestart
    username: admin_gestart
    password: admin@gestart
    initialization-mode: always
    continue-on-error: true
    platform: postgres
  liquibase:
   contexts: dev
   enabled: true
  doc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      enabled: true
      path: /v3/api-docs
#sicomm:
#  mail:
#    base-url: http://localhost:4200

